#ifndef _LINUX_KMEM_DEFRAGD_H
#define _LINUX_KMEM_DEFRAGD_H

#define MEM_DEFRAG_SCAN				0
#define MEM_DEFRAG_MARK_SCAN_ALL	1
#define MEM_DEFRAG_CLEAR_SCAN_ALL	2
#define MEM_DEFRAG_DEFRAG			3
#define MEM_DEFRAG_THP_COMPACT		4
#define MEM_DEFRAG_CONTIG_SCAN		5
#define MEM_DEFRAG_PAGEBLOCK_SCAN	6
#define MEM_DEFRAG_FLUSH_TLB		7

enum mem_defrag_action {
	MEM_DEFRAG_FULL_STATS = 0,
	MEM_DEFRAG_DO_DEFRAG,
	MEM_DEFRAG_CONTIG_STATS,
};


#endif /* _LINUX_KMEM_DEFRAGD_H */
